### PR TITLE
Add variable recreate_missing_package

### PR DESCRIPTION
**Pull request by frank-bee**
See Readme of the underlying module (FAQ section). This is required when using this module in CI/CD

### CODE REVIEW

**Comment by frank-bee** [comment]
I also added the latest code from aws lambda templates for multi-secret-lambda . not tested because we use single-secret-lambda, but should work

**Comment by JCapriotti** [comment]
@frank-bee Thanks; sorry for not looking at this sooner. Glad you mentioned you updated the Lambda using the template; was that all just copied as-is?

**Comment by frank-bee** [comment]
Yes, copied as-is. 

BTW, I wonder if there is a way to add the python dependencies when deploying the lambda ? having binaries here in the code is not so nice. also a problem of trust , not?

**Comment by JCapriotti** [comment]
Sounds good; I'll take another look and merge. Your change looks pretty straight-forward.

Regarding Python dependencies, that is a good point. I generally like to copy-paste things without modification (as long as they work), but I can see how binaries in an open source package could pose some discomfort. 

The thing that makes it awkward is some of those libs (namely `libcrypto.so.1.0.0`) are specific to the platform, so require additional build steps depending on what platform you're deploying from. For now, I'm going to create an issue for that topic.

**Comment by JCapriotti** [comment]
I merged this and will add a new version to the TF registry... sorry I lost track of this!

I wasn't able to rotate the password in the example TF, but I suspect that was due to a difference in my current vs original environment. I'll see if I can update that to satisfy my ability to test.

**Pull request merged**
